require 'faker'


# Line.create(name: "1 Bronzeville/Union Station", bus?: true)
# Line.create(name: "2 Hyde Park Express", bus?: true)
# Line.create(name: "3 King Drive", bus?: true)
# Line.create(name: "4 Cottage Grove - OWL", bus?: true)
# Line.create(name: "N5 South Shore Night Bus - OWL", bus?: true)
# Line.create(name: "6 Jackson Park Express", bus?: true)
# Line.create(name: "7 Harrison", bus?: true)
# Line.create(name: "8 Halsted", bus?: true)
# Line.create(name: "8A South Halsted", bus?: true)
# Line.create(name: "9 Ashland - OWL", bus?: true)
# Line.create(name: "X9 Ashland Express", bus?: true)
# Line.create(name: "10 Museum of Science &amp; Industry", bus?: true)
# Line.create(name: "11 Lincoln", bus?: true)
# Line.create(name: "12 Roosevelt", bus?: true)
# Line.create(name: "J14 Jeffery Jump", bus?: true)
# Line.create(name: "15 Jeffery Local", bus?: true)
# Line.create(name: "18 16th-18th", bus?: true)
# Line.create(name: "19 United Center Express", bus?: true)
# Line.create(name: "20 Madison - OWL", bus?: true)
# Line.create(name: "21 Cermak", bus?: true)
# Line.create(name: "22 Clark - OWL", bus?: true)
# Line.create(name: "24 Wentworth", bus?: true)
# Line.create(name: "26 South Shore Express", bus?: true)
# Line.create(name: "28 Stony Island", bus?: true)
# Line.create(name: "29 State", bus?: true)
# Line.create(name: "30 South Chicago", bus?: true)
# Line.create(name: "34 South Michigan - OWL", bus?: true)
# Line.create(name: "35 31st/35th", bus?: true)
# Line.create(name: "36 Broadway", bus?: true)
# Line.create(name: "37 Sedgwick", bus?: true)
# Line.create(name: "39 Pershing", bus?: true)
# Line.create(name: "43 43rd", bus?: true)
# Line.create(name: "44 Wallace-Racine", bus?: true)
# Line.create(name: "47 47th", bus?: true)
# Line.create(name: "48 South Damen", bus?: true)
# Line.create(name: "49 Western - OWL", bus?: true)
# Line.create(name: "X49 Western Express", bus?: true)
# Line.create(name: "49B North Western", bus?: true)
# Line.create(name: "50 Damen", bus?: true)
# Line.create(name: "51 51st", bus?: true)
# Line.create(name: "52 Kedzie/California", bus?: true)
# Line.create(name: "52A South Kedzie", bus?: true)
# Line.create(name: "53 Pulaski - OWL", bus?: true)
# Line.create(name: "53A South Pulaski", bus?: true)
# Line.create(name: "54 Cicero", bus?: true)
# Line.create(name: "54A North Cicero/Skokie Blvd.", bus?: true)
# Line.create(name: "54B South Cicero", bus?: true)
# Line.create(name: "55 Garfield - OWL", bus?: true)
# Line.create(name: "55A 55th/Austin", bus?: true)
# Line.create(name: "55N 55th/Narragansett", bus?: true)
# Line.create(name: "56 Milwaukee", bus?: true)
# Line.create(name: "57 Laramie", bus?: true)
# Line.create(name: "59 59th/61st", bus?: true)
# Line.create(name: "60 Blue Island/26th - OWL", bus?: true)
# Line.create(name: "62 Archer - OWL", bus?: true)
# Line.create(name: "62H Archer/Harlem", bus?: true)
# Line.create(name: "63 63rd - OWL", bus?: true)
# Line.create(name: "63W West 63rd", bus?: true)
# Line.create(name: "65 Grand", bus?: true)
# Line.create(name: "66 Chicago - OWL", bus?: true)
# Line.create(name: "67 67th-69th-71st", bus?: true)
# Line.create(name: "68 Northwest Highway", bus?: true)
# Line.create(name: "70 Division", bus?: true)
# Line.create(name: "71 71st/South Shore", bus?: true)
# Line.create(name: "72 North", bus?: true)
# Line.create(name: "73 Armitage", bus?: true)
# Line.create(name: "74 Fullerton", bus?: true)
# Line.create(name: "75 74th-75th", bus?: true)
# Line.create(name: "76 Diversey", bus?: true)
# Line.create(name: "77 Belmont - OWL", bus?: true)
# Line.create(name: "78 Montrose", bus?: true)
# Line.create(name: "79 79th", bus?: true)
# Line.create(name: "80 Irving Park", bus?: true)
# Line.create(name: "81 Lawrence - OWL", bus?: true)
# Line.create(name: "81W West Lawrence", bus?: true)
# Line.create(name: "82 Kimball-Homan", bus?: true)
# Line.create(name: "84 Peterson", bus?: true)
# Line.create(name: "85 Central", bus?: true)
# Line.create(name: "85A North Central", bus?: true)
# Line.create(name: "86 Narragansett/Ridgeland", bus?: true)
# Line.create(name: "87 87th - OWL", bus?: true)
# Line.create(name: "88 Higgins", bus?: true)
# Line.create(name: "90 Harlem", bus?: true)
# Line.create(name: "91 Austin", bus?: true)
# Line.create(name: "92 Foster", bus?: true)
# Line.create(name: "93 California/Dodge", bus?: true)
# Line.create(name: "94 South California", bus?: true)
# Line.create(name: "95W West 95th", bus?: true)
# Line.create(name: "95E 93rd-95th", bus?: true)
# Line.create(name: "96 Lunt", bus?: true)
# Line.create(name: "97 Skokie", bus?: true)
# Line.create(name: "X98 Avon Express", bus?: true)
# Line.create(name: "100 Jeffery Manor Express", bus?: true)
# Line.create(name: "103 West 103rd", bus?: true)
# Line.create(name: "106 East 103rd", bus?: true)
# Line.create(name: "108 Halsted/95th", bus?: true)
# Line.create(name: "111 111th/King Drive", bus?: true)
# Line.create(name: "111A Pullman Shuttle", bus?: true)
# Line.create(name: "112 Vincennes/111th", bus?: true)
# Line.create(name: "115 Pullman/115th", bus?: true)
# Line.create(name: "119 Michigan/119th", bus?: true)
# Line.create(name: "120 Ogilvie/Streeterville Express", bus?: true)
# Line.create(name: "121 Union/Streeterville Express", bus?: true)
# Line.create(name: "124 Navy Pier", bus?: true)
# Line.create(name: "125 Water Tower Express", bus?: true)
# Line.create(name: "126 Jackson", bus?: true)
# Line.create(name: "128 Soldier Field Express", bus?: true)
# Line.create(name: "130 Museum Campus", bus?: true)
# Line.create(name: "132 Goose Island Express", bus?: true)
# Line.create(name: "134 Stockton/LaSalle Express", bus?: true)
# Line.create(name: "135 Clarendon/LaSalle Express", bus?: true)
# Line.create(name: "136 Sheridan/LaSalle Express", bus?: true)
# Line.create(name: "143 Stockton/Michigan Express", bus?: true)
# Line.create(name: "146 Inner Drive/Michigan Exp.", bus?: true)
# Line.create(name: "147 Outer Drive Express", bus?: true)
# Line.create(name: "148 Clarendon/Michigan Express", bus?: true)
# Line.create(name: "151 Sheridan", bus?: true)
# Line.create(name: "152 Addison", bus?: true)
# Line.create(name: "155 Devon", bus?: true)
# Line.create(name: "156 LaSalle", bus?: true)
# Line.create(name: "157 Streeterville/Taylor", bus?: true)
# Line.create(name: "165 West 65th", bus?: true)
# Line.create(name: "169 69th-UPS Express", bus?: true)
# Line.create(name: "171 U. of Chicago/Hyde Park", bus?: true)
# Line.create(name: "172 U. of Chicago/Kenwood", bus?: true)
# Line.create(name: "192 U. of Chicago Hospitals Express", bus?: true)
# Line.create(name: "201 Central/Ridge", bus?: true)
# Line.create(name: "205 Chicago/Golf", bus?: true)
# Line.create(name: "206 Evanston Circulator", bus?: true)
# Line.create(name: "Brown line", bus?: false)
# Line.create(name: "Purple line", bus?: false)
# Line.create(name: "Red line", bus?: false)
# Line.create(name: "Blue line", bus?: false)
# Line.create(name: "Orange line", bus?: false)
# Line.create(name: "Pink line", bus?: false)
# Line.create(name: "Green line", bus?: false)
# Line.create(name: "Yellow line", bus?: false)


# 10.times do
#     User.create(username: Faker::Internet.user_name, email: Faker::Internet.email, password: 'password')
# end

# 100.times do
#     Subscription.create(
#       user_id: rand(1..10),
#       line_id: rand(1..137),
#       priority: rand(1..3)
#       )
# end
